### PR TITLE
Status Report

### PR DESCRIPTION
**Pull request by shivanshuag**
### System

A few changes from the drupal 7 version
- [x] Pass - Passes in a default drupal installation.
- [x] Warn - Not sure how to test this, but should work.
- [x] Fail - Not sure how to test this, but should work

### CODE REVIEW

**Comment by fluxsauce** [comment]
>  Warn - Not sure how to test this, but should work.
> Fail - Not sure how to test this, but should work

You wrote the code and should understand how it works, please provide test instructions. I can't review this unless you provide instructions on how to test it.

**Comment by fluxsauce** [comment]
The purpose of writing the instructions is to detail that you understand both how Drupal and site_audit works. Also, it allows me to fully exercise the system in the way you intended, along with my own testing.

**Comment by shivanshuag** [comment]
This check just gives the drupal's status report and calculates score based on that. Testing for whether the check gives a warning or fails will just test the condition where the score is just compares to the pre-defined threshold. So, I think just seeing the the report it outputs and comparing it with the original drupal status report at `admin/reports/status` and checking that the score is correct should be sufficient.
Writing instructions for doing things that would bring enough checks in the drupal's status report to a level of `error` or `warning` so that the overall `System` check fails, in my view, will be overkill.

**Comment by fluxsauce** [comment]
All set, thanks! I took care of the merge conflict.

**Pull request merged**
